### ISSUE TITLE
Silent exit after <10 seconds

### ISSUE THREAD

**Issue by dandv** [pdfarranger/pdfarranger#1055]
I installed PDF Arranger 1.10.1 on Fedora 38 via Flatpak. After I launch it, no matter what I do (even nothing), it exits in about 10 seconds. Nothing is displayed in the console.

To Reproduce
------------

1.  Run `flatpak run --branch=stable --arch=x86_64 --command=pdfarranger --file-forwarding com.github.jeromerobert.pdfarranger`
2.  Wait 10 seconds

System and Versions
-------------------
-   pikepdf version  - I don't have this installed.

**Comment by dreua** [comment]
The flatpak from flathub vor from fedoras repository?
I'll try to reproduce asap, sounds like a crash to me. But 10 seconds sounds really strange, this issue triggers my curiosity.

**Comment by dandv** [comment]
I installed it via Discover:

![image](https://github.com/pdfarranger/pdfarranger/assets/33569/268b8663-c996-49b4-a73d-575c9f321a9b)

**Comment by dreua** [comment]
Doesn't reproduce for me unfortunately, also on Fedora 38. You can use the "Sources" dropdown at the top right to install an other package version and see if one of those behaves. Is there a reason for the "branch" and "arch" flags i.e. are you on a different arch?

If you want to debug this further:
Try running `journacltl --follow` in another terminal (may need sudo) and see if it outputs anything interesting at the moment PDF Arranger closes.

It is possible to run strace in a flatpak if you want to try that:
```
flatpak install runtime/org.gnome.Sdk/x86_64/45
flatpak run --branch=stable --arch=x86_64 --devel --command=bash --file-forwarding com.github.jeromerobert.pdfarranger -c "strace pdfarranger"
```
Feel free to send me an email (link in bio) with the last lines as I'm not sure whether it is safe to post strace output publicly.

**Comment by dreua** [comment]
Closing for lack of feedback. I'd still be curious to find the cause but it might be hard without direct access to the machine.

**Comment by dandv** [comment]
Sorry for the lack of feedback!

The CLI flags were copied from the Plasma Application Launcher entry:

![image](https://github.com/pdfarranger/pdfarranger/assets/33569/778b7448-1af0-4f88-ae1b-2e25ef25e955)

`arch` outputs `x86_64`.

`journalctl` didn't show anything when PDF Arranger exited. I launched it three times:

```
May 22 01:36:53 fedora plasmashell[19121]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
May 22 01:36:55 fedora systemd[18570]: Started app-com.github.jeromerobert.pdfarranger-bee19e63e83f4d389ccc2235c8ad05d6.scope - PDF Arranger.
May 22 01:36:55 fedora systemd[18570]: Started app-flatpak-com.github.jeromerobert.pdfarranger-625723.scope.
May 22 01:36:55 fedora xdg-desktop-portal-kde[19178]: xdp-kde-settings: Group  "org.freedesktop.appearance"  doesn't exist
May 22 01:36:55 fedora xdg-desktop-portal-kde[19178]: xdp-kde-settings: Namespace  "org.gnome.desktop.a11y.interface"  is not supported
May 22 01:37:13 fedora plasmashell[19121]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
May 22 01:37:15 fedora systemd[18570]: Started app-com.github.jeromerobert.pdfarranger-0b75a674070f4a24bdc1dad3b876a87b.scope - PDF Arranger.
May 22 01:37:15 fedora systemd[18570]: Started app-flatpak-com.github.jeromerobert.pdfarranger-625751.scope.
May 22 01:37:15 fedora xdg-desktop-portal-kde[19178]: xdp-kde-settings: Group  "org.freedesktop.appearance"  doesn't exist
May 22 01:37:15 fedora xdg-desktop-portal-kde[19178]: xdp-kde-settings: Namespace  "org.gnome.desktop.a11y.interface"  is not supported
May 22 01:37:25 fedora plasmashell[19121]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
May 22 01:37:27 fedora systemd[18570]: Started app-com.github.jeromerobert.pdfarranger-a0fd78afa3654502b027865fb10c6233.scope - PDF Arranger.
May 22 01:37:27 fedora systemd[18570]: Started app-flatpak-com.github.jeromerobert.pdfarranger-625775.scope.
May 22 01:37:27 fedora xdg-desktop-portal-kde[19178]: xdp-kde-settings: Group  "org.freedesktop.appearance"  doesn't exist
May 22 01:37:27 fedora xdg-desktop-portal-kde[19178]: xdp-kde-settings: Namespace  "org.gnome.desktop.a11y.interface"  is not supported
```


I installed v1.10.1 from the Snap source and it behaves properly. (BTW, it has a different author - maybe the packager? Is that expected?)

![image](https://github.com/pdfarranger/pdfarranger/assets/33569/66804b48-a675-43bf-9fd4-df177eb9ff52)

**Comment by dreua** [comment]
I'm not familiar with snap an its stores but that is the name of the packager.

Unfortunately the journal didn't help. Strace would be the next best debugging tool in my knowledge but that may be complicated without direct access. If the snap works for you I'm happy to leave it like that.

**Comment by drgcms** [comment]
I am having same problems on KDE Neon 6.0 in x11 session. I am not using program regularly so it might happened after updating to KDE 6.0.

I just updated to last flatpack version and the problem persists.


I get this messages when starting from prompt:
---------------------
$ flatpak -v --ostree-verbose run --file-forwarding com.github.jeromerobert.pdfarranger /mnt/arhiv/temp/11.pdf

F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/rems/.local/share/flatpak
F: Opening user flatpak installation at path /home/rems/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/com.github.jeromerobert.pdfarranger/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/rems/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/45/8cfcf19ef856011fd7e09d58389d1b3761a4b80beb6504516e010eae003494fd/files/lib32 does not exist
F: Cleaning up unused container id 2557953025
F: Cleaning up per-app-ID state for com.github.jeromerobert.pdfarranger
F: Allocated instance id 3499037911
F: Add defaults in dir /com/github/jeromerobert/pdfarranger/
F: Add locks in dir /com/github/jeromerobert/pdfarranger/
F: Disallowing network access
F: Allowing host-fs access
F: skipping export for path /usr/libx32
F: Allowing wayland access
F: Allowing x11 access
F: Running 'bwrap --args 39 xdg-dbus-proxy --args=41'
F: Running 'bwrap --args 39 pdfarranger /mnt/arhiv/temp/11.pdf'
--------------------

All messages are written at program start. There is no additional message after window self closes. 

by
TheR

**Comment by drgcms** [comment]
After I've already written this messages I tried to run as sudo and it works. It looks like some permission error.

-------------
$ sudo -i  flatpak -v --ostree-verbose run --file-forwarding com.github.jeromerobert.pdfarranger /mnt/arhiv/temp/11.pdf
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /root/.local/share/flatpak
F: Opening user flatpak installation at path /root/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/com.github.jeromerobert.pdfarranger/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /root/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/45/8cfcf19ef856011fd7e09d58389d1b3761a4b80beb6504516e010eae003494fd/files/lib32 does not exist
F: Cleaning up unused container id 873791972
F: Cleaning up per-app-ID state for com.github.jeromerobert.pdfarranger
F: Allocated instance id 687395982
F: Add defaults in dir /com/github/jeromerobert/pdfarranger/
F: Add locks in dir /com/github/jeromerobert/pdfarranger/
F: Disallowing network access
F: Allowing host-fs access
F: skipping export for path /usr/libx32
F: Allowing wayland access
F: Allowing x11 access
F: Failed to run in transient scope: No systemd user session available, cgroups not available
F: Running 'bwrap --args 36 xdg-dbus-proxy --args=41'
F: Running 'bwrap --args 38 pdfarranger /mnt/arhiv/temp/11.pdf'
--------

by
TheR
