### ISSUE TITLE
Build error on Windows: "cannot find file/directory named `C:/msys64/mingw64/share/icons/Adwaita..."

### ISSUE THREAD

**Issue by thedavidyoungblood** [pdfarranger/pdfarranger#1093]
**Describe the bug**
---------------------
Error: cannot find file/directory named `C:/msys64/mingw64/share/icons/Adwaita/16x16/status/image-missing-symbolic.symbolic.png`.

A clear and concise description of what the bug is:
During the build process of PDF Arranger on Windows using MSYS2, the build fails because it cannot find the specified icon file in the given directory. This issue prevents the creation of the MSI and ZIP distributions.

**To Reproduce**
----------------
1. Clone the PDF Arranger repository:
   ```sh
   git clone https://github.com/pdfarranger/pdfarranger.git
   ```
2. Navigate to the pdfarranger directory:
   ```sh
   cd pdfarranger
   ```
3. Run the build commands:
   ```sh
   /mingw64/bin/python3.exe ./setup.py build
   /mingw64/bin/python3.exe setup_win32.py bdist_msi
   /mingw64/bin/python3.exe setup_win32.py bdist_zip
   ```
4. See the error.

**Expected behavior**
---------------------
A clear and concise description of what you expected to happen:
The build process should complete successfully without errors, and the MSI and ZIP distributions should be created.

**Input files**
---------------
Check if the bug appears only with some PDF or image files. If the bug is specific to some files, please attach one to the issue.

**Screenshots**
--------------

**System and Versions**
-----------------------
- PDF Arranger version: Latest from GitHub repository.
- pikepdf version: Installed via pip.
- OS name and version: Windows with MSYS2.

**Comment by dreua** [comment]
I've never built it on Windows, maybe someone else can help you or you could try it in the Docker container. It works fine in GHA with this container:
https://github.com/pdfarranger/pdfarranger-docker-ci/tree/main/win32
https://github.com/pdfarranger/pdfarranger/blob/a38e05766462a20184e7e513e0807f73946546f4/.github/workflows/install.yml#L77-L94

**Comment by kbengs** [comment]
I will try to go through the Windows build steps later. In the mean time you could try to remove the file in setyp_win32.py on line 52. I think it is not needed.

**Comment by varsteel-jeremyzaretski** [comment]
I have also encountered this issue. This issue appears to be related to the removal of the "status" subdirectory from the Adwaita icons.

"C:\msys64\mingw64\share\icons\Adwaita\16x16" exists.

"C:\msys64\mingw64\share\icons\Adwaita\16x16\status" does not exist.

In [this link from 2023-11](https://old.reddit.com/r/archlinux/comments/17nva3d/usrshareiconsadwaita16x16status_missing_from/), wherein the user "vimdiff" encountered this very error due to this missing subdirectory and wrote the following: 

> The folder and the .png icons it contained were removed after updating to 45.0-1. Folder is present with 44.0-1.
> 
> I don't see it being removed from upstream code. It's not explicitly removed from [the last change to packaging](https://gitlab.archlinux.org/archlinux/packaging/packages/adwaita-icon-theme/-/commit/1c5ca4a877b2170f34b78014cb092155d95f27ac) either.

I also found [this](https://forum.xfce.org/viewtopic.php?id=15735) XFCE forum thread from 2022-(04/05) wherein the user "hardrock" reported several broken icons from the same repository package. The forum administrator "ToZ" stated [the following](https://forum.xfce.org/viewtopic.php?pid=66905#p66905): 

> [...]
> If you are using the adwaita icon theme, then it was recently updated and removed/renamed many of those icons. The AUR has an adwaita-icon-theme-41 - which is the state of the icon theme prior to 42. This icon theme will replace the newer version, but this will also break any newer libadwaita 42 gnome apps.
> 
> Here are some instructions that will install the 41 version locally and link into the newer 42 version of the icon theme -best of both worlds:
> [...]

That post was then eventually followed by [the following](https://forum.xfce.org/viewtopic.php?pid=67052#p67052): 

> Hmm. Now that script isn't working for me either. I've changed it to use git to clone the repository and tested that it works. Give this one a try.
> 
> But first, delete the existing ~/.local/share/icons/Adwaita-41 folder.

Wherein ToZ provided the following script:

```
#!/bin/sh

# clone the repository and checkout the 41 commit
git clone https://gitlab.gnome.org/GNOME/adwaita-icon-theme.git
cd adwaita-icon-theme
git checkout 8670d0eb2414c1ac16d927da5d1a22142ba5e346

# build and install the theme
autoreconf -fvi
./autogen.sh --prefix=$HOME/.local
make
make install

# rename the icon theme so it doesn't interfere with the newer version
mv $HOME/.local/share/icons/Adwaita $HOME/.local/share/icons/Adwaita-41
sed -i 's/Adwaita/Adwaita-41/' $HOME/.local/share/icons/Adwaita-41/index.theme

# have it inherit from the newer theme so that newer 42 icons are found and used
sed -i 's/Inherits=hicolor/Inherits=Adwaita/' $HOME/.local/share/icons/Adwaita-41/index.theme

# update the icon cache
gtk-update-icon-cache $HOME/.local/share/icons/Adwaita-41

# select Adwaita-41.1 from Settings Manager > Appearance > Icons, or
xfconf-query -c xsettings -p /Net/IconThemeName -t string -s "Adwaita-41" --create

# restart the panel
xfce4-panel -r
```

Unfortunately, I am unfamiliar with XFCE, MSYS2, MINGW, and the GIT command line.

Trying to grafts the icons and "status" subdirectory from revision 45.0-1 onto the current revision might be a short-term solution but it is not something that I know how to do at this moment in time. A better long-term solution would be to remove the dependency on those icons or use a different set of icons altogether.

**Comment by varsteel-jeremyzaretski** [comment]
Curious. I attempted to re-run _almost_ all of the steps outlined in [the Windows build instructions](https://github.com/pdfarranger/pdfarranger/blob/main/Win32.md).

The exceptions being that:

- I did not install MSYS2 because it remained installed after my first build attempt.
- I had to delete the `C:\msys64\home\jeremy.zaretski\pdfarranger` directory in order to the `git` clone command to succeed.

The same error occurred again. This suggests that my clone of the main repository does not (yet) include your modification.

Unfortunately, I have yet to figure out how to use `git` to apply [your commit from your repository](https://github.com/kbengs/pdfarranger/commit/7ede25f53ed60227b8b696ac12d249004352b5b4) to my clone of the main repository, so I manually applied your commit.

The good news is that it built properly. Huzzah! There's now a lovely MSI and ZIP file in the "pdfarranger/dist" directory!

**Comment by kbengs** [comment]
I merged the change so now it is in main.

A msi and zip is automatically built on every pull request and merge on the actions page, for example here:
https://github.com/pdfarranger/pdfarranger/actions/runs/9516776481
If you don't want to build it yourself. :smiley:

**Comment by varsteel-jeremyzaretski** [comment]
Ah yes. I can see the build-win32 step. Thank you.

Alrighty. I will run the Windows build instructions again.

...

Build successful. Huzzah!

Always nice to ensure that the build instructions work. Thanks again.
