### ISSUE TITLE
Output is always PDF Version 1.3

### ISSUE THREAD

**Issue by greybit** [pdfarranger/pdfarranger#1099]
Describe the bug
----------------

Output is always PDF version 1.3, even if features are used that require a newer PDF version.

To Reproduce
------------

1.  Import 1 or more PDFs into PDF Arranger
2.  Save

Expected behavior
-----------------

Use the newest PDF Version of all imported PDFs... maybe?

Input files
-----------

Any

Screenshots
-----------

A PDF saved with PDF Arranger tested with Acrobat Preflight for version compatibility 1.3:

<img width="329" alt="AcrobatPreflight" src="https://github.com/pdfarranger/pdfarranger/assets/16707249/aa41577d-1e7f-4892-97cb-16ed747b1d31">

System and Versions
-------------------

Windows 10 with PDF Arranger 1.10 or older.

**Comment by dreua** [comment]
From what I see we don't set anything, therefore qpdf decides that automatically. I could imagine, though, that it can't derive it from the input files if it only gets the pages. Some more digging would be necessary to be sure about that.

A pikepdf example explicitly calculates and sets the maximum of all input files, I guess we could also do that: https://pikepdf.readthedocs.io/en/latest/topics/pages.html#merge-concatenate-pdf-from-several-pdfs

Or we keep it simple and just set it fixed to something recent like 1.7 or 2.0?

**Comment by greybit** [comment]
I testet some more PDFs from Version 1.0 up to 2.0 (with features that are not supported in version 1.3). The output of PDF Arranger is always version 1.3. So it looks like "automatically" really means "always version 1.3".

> Or we keep it simple and just set it fixed to something recent like 1.7 or 2.0?

I checked how Acrobat handle merged PDFs.
Saved PDFs have version 1.6 if imported PDFs are 1.6 or lower.
If at least one PDF have version 1.7, the output ist 1.7.
If at least one PDF have version 2.0, the output ist 2.0.

**Comment by dreua** [comment]
I don't know enough about PDFs: Would setting `min_version` to 2.0  have any downsides? Otherwise the "max" approach from the pikepdf example) seems like the best idea. (Not because of the way Acrobat is handling it but because it would make sense :wink: )

**Comment by greybit** [comment]
> Would setting min_version to 2.0 have any downsides?

I changed the first line of a PDF from `%PDF-1.3` to `%PDF-2.0` with a text editor and opened both with a older version of Acrobat (V5.0). `%PDF-1.3` and `%PDF-2.0` get displayed fine, however for the file `%PDF-2.0`, this massage come before the file get displayed.
`This file may contain newer information than this viewer can support. It may not open or display correctly [...]`

So, has it any downsides? Yes, if you use a outdated viewer!

(Sorry for using Acrobat as a example again😉)

**Comment by AaronHarris** [comment]
Would suggest going with the case-basis greybit suggested. You want to output the lowest version available based on source files to ensure outputs can be read with old software.

**Comment by dreua** [comment]
> You want to output the lowest version available based on source files to ensure outputs can be read with old software.

I'm not really sure I want that tbh. Not forcing anyone to update to the bleeding edge of course, but I believe we can expect users to have a reasonably recent PDF reader. Running outdated software is also a security risk, I don't think we should go above and beyond to support people engaging in risky behavior. Pinning it to 2.0 might be to much, though, I don't know enough about PDFs to really judge this.

If someone implements the "min" approach I'd still suggest using 1.3 as a bare minimum just in case pikepdf has any issues below that.

**Comment by AaronHarris** [comment]
It's not about the software, it's about the file compatibility. The version is just there to signify which file features are used. It's like expecting that your web server must only respond to HTTP2 requests because HTTP1.1 requests are somehow "outdated" even though simple HTTP requests only use features of HTTP1.0/1.1. Newer software will maintain backwards compatibility with older files, and it's the software that is responsible for patching vulnerabilities, not the file itself. Older files don't become unreadable just because you use newer software, especially for a standardized format like PDF. Hopefully that clarifies my thinking. I think either going the max(sourcefiles) or the 1.3/1.6/1.7/2.0 tiered approach are good options.

**Comment by dreua** [comment]
I don't think the HTTP-analogy is adequate here because a server can respond to respond differently to requests based on the requested versions. We have to output one file with one version, there is no request with any information on which version to generate. You seem to have misunderstood me on a few details here but the conclusion is all the same.

Does anyone have data on the prevalence of PDF readers not supporting PDF 2.0?

**Comment by kbengs** [comment]
Closed with #1139
