### ISSUE TITLE
Something wrong with the source code file hash

### ISSUE THREAD

**Issue by PiPiKKP0P0** [pdfarranger/pdfarranger#1119]
Hello,
Since you don't provide hash values, I went to look for them on the SourceForge.net site. Having downloaded the .msi and .zip files for Windows as well as the codesource.zip file; I checked them with the PowerShell command Get-Filehash.
For the Windows files, the hash values ​​provided by SourceForge.net correspond well to the hashes of the files that I downloaded from GitHub. 
For the codesource.zip file whose download name from GitHub is "**pdfarranger-1.11.0.zip**" and the size of **578,719 bytes**, the SHA1 is:
**c41eaddba11722d9933e7eab4de40060eec7781f**
For the codesource.zip file whose download name from SourceForge is "**1.11.0 source code.zip**" and the size is **582,385 bytes**, the SHA1 is:
**3bfb2ed373b2a3d5ec73692b3da29df39a8654c6**
The download address from SourceForge:
https://sourceforge.net/projects/pdf-arranger.mirror/files/1.11.0/

So the values ​​are different, as well as the file names... Which is the right file please? Thank you.

**Comment by dreua** [comment]
A hash value that you get from the same site and which is under the control of the same people and transferred through the same https connection will not make your download any safer. That's why most projects around here don't provide hash values.

This repository here on Github is the official and correct download site; I do not know what Sourceforge is doing there, please contact their support about that. (Afaik they put up this mirror without any communication with us. They are probably allowed to do so due to the open source license but it feels like they are doing this just to increase their profits without giving anything back.)
