### ISSUE TITLE
the software just print the first page

### ISSUE THREAD

**Issue by dzwdev** [pdfarranger/pdfarranger#1161]
i have a pdf file with 10 pages when i try to print those pages with Pdf arranger with 2 pages per side the output gives just the first pages repeated.

**Comment by kbengs** [comment]
Could you give us the OS name and version of PDF Arranger. Maybe also a printscreen of the print dialog.

**Comment by dzwdev** [comment]
os details:
Operating System: EndeavourOS 
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.1
Kernel Version: 6.6.63-1-lts (64-bit)
Graphics Platform: Wayland

pdfarranger version: 1.11.1

![image](https://github.com/user-attachments/assets/cfa0045e-abcf-42a8-b020-2cf39f702ca5)

**Comment by kbengs** [comment]
I also have KDE but it works fine for me. Do you see the same issue with any PDF? If not could you share the PDF which has this issue?

**Comment by dzwdev** [comment]
> I also have KDE but it works fine for me. Do you see the same issue with any PDF? If not could you share the PDF which has this issue?


[011.pdf](https://github.com/user-attachments/files/18105048/011.pdf)

**Comment by kbengs** [comment]
Thanks. With these steps I can reproduce the issue:

1. Open the attached PDF (or any PDF where the pages are images)
2. Select all and scale the pages to 101% ([so that this else will run](https://github.com/pdfarranger/pdfarranger/blob/f8d9c5b9a8b2cf0ec6d8504c245bc9d64bfc9ef6/pdfarranger/exporter.py#L684))
3. Print to PDF
-> all pages looks as page 1

This change seems to "fix" the issue:
```
diff --git a/pdfarranger/exporter.py b/pdfarranger/exporter.py
index deb55c0..69cb26c 100644
--- a/pdfarranger/exporter.py
+++ b/pdfarranger/exporter.py
@@ -696,7 +696,7 @@ class PrintOperation(Gtk.PrintOperation):
             buf = io.BytesIO()
             export_doc(self.pdf_input, [p], {}, [buf], None)
             page = Poppler.Document.new_from_data(buf.getvalue()).get_page(0)
-            page.render_for_printing(cairo_ctx)
+            page.render(cairo_ctx)
```

This makes me think its a poppler bug. Anyone want to continue debugging and maybe report bug to poppler?

**Comment by kbengs** [comment]
I am working on a fix
