### ISSUE TITLE
The opening "note" appears on every launch

### ISSUE THREAD

**Issue by tjsuominen** [pdfarranger/pdfarranger#1162]
The opening note (see screenshot) appears every time I open the app (despite the checkmark).

I have the portable version (1.11.0) installed in "C:\Program Files\Tools\PDF Arranger" -folder. My computer is a Windows 11.

Also note, the config.ini (same directory) is 0 (zero) bytes with no content.

![pdfa](https://github.com/user-attachments/assets/16cdcd34-4313-4e55-b951-ffaa0a2060f8)

**Comment by dreua** [comment]
How did you "install" the portable version in the Program Files directory? From what I remember of windows there is a lot which could go wrong there due to filesystem access restrictions. I could very well imagine that the executable is unable to read/write the ini file there. (And there is also a system of filesystem overlays for the user apps which try to write there as a user iirc.) I'm not into windows so please do not expect me to debug this further, I suggest you try installing the portable version in your personal user folder where file access is not an issue. Otherwise there is the msi installer which has been reported to work and I think it can even be installed system wide with the right flags.

**Comment by dreua** [comment]
Could you try to change any other setting and see if that persists to another launch? I'd assume that no settings are stored / loaded here.

**Comment by tjsuominen** [comment]
Simply copying the files. But understood, I'll do some rework during the weekend and get back.

**Comment by tjsuominen** [comment]
Yeah, the 'trick' was to install the app via Windows installer to the 'proposed' directory. No more popping up of the note.

Yet, I would like to add that I have say 35+ properly working apps in my C:\Program Files\Tools\<Appfolder> installed. Perhaps placing just the requested ini (etc.) to the \users\<username>\Appdata\Local\Programs\ would be a better option?

Just a thought.

Keep up the great work, using this utility on a daily basis!

**Comment by dreua** [comment]
If there is any (preferably broadly accepted) standard we are violating here let me know. Otherwise I'd always assume a "portable" app would put all config files into its current directory, how else would it be portable, say on a USB stick or something?
