### ISSUE TITLE
Add "Insert blank (empty) page" option

### ISSUE THREAD

**Issue by Nokia808** [pdfarranger/pdfarranger#244]
Hi.

This feature is highly needed by many users, for example to add notes within empty page.

I suggest the following, which suitable to current design of pdfarranger:
User when select a page (any page), then right click this selected page, the right click list appear & containing - in addition to current options - 2 new options: "add empty page before" & "add empty page after". The size of new empty page should be the same of size of selected page.

**Comment by jeromerobert** [comment]
This is again about porting a feature of pdfmixertool to pdfarranger. As that one should be easy, why not.

**Comment by jeromerobert** [comment]
pikpdf have a dedicated method for that <https://pikepdf.readthedocs.io/en/latest/api/main.html#pikepdf.Pdf.add_blank_page>.

We could also consider blanking existing pages. To blank a page with pikepdf:
```python
ydoc.pages[pageid].Contents = mydoc.make_stream(pikepdf.unparse_content_stream([]))
```
This is for the export. I don't know yet what to do for the poppler/rendering part.

**Comment by Nokia808** [comment]
@jeromerobert 
Thank you for your care about this issue.

One thing bring my attention: "blanking EXISTING page" ! Do you mean by this that pikepdf has ability to SECURELY remove contents within a page ? If yes, then this mean that pikepdf has ability for secure redaction.

**Comment by angsch** [comment]
@jeromerobert As you mention in #199, the page scaling support will most likely result in the creation of temporary files. Do you want to go for a temporary file for the creation of blank pages as well?

When you select multiple pages, what is the expected behavior of 'insert blank page after'? A single blank page after the last selected page? Or a blank page after each selected page? This choice is connected with what size the new blank page has. Consider, for example, a selection of an A0 page and an A4 page.

**Comment by dreua** [comment]
@angesch about temporary files: I'd say do whatever works best or results in the cleanest code but it will most likely be temp files. More on that #199.

About multiple pages: Good question, what do you think is best? I see a small use case in inserting a blank page after/before each page of a selection (print a range of pages virtually non-duplex while your printer considers them all duplex). In this case I'd take the dimensions for each blank page from their respective previous/following page. If people want just one page, they can undo and will learn to just select one page. On the other hand, keeping it simple and just inserting always one page is fine with me, too. (I'd take the dimensions like this: "Insert before" - first selected page; "insert after" - last selected page.)

**Comment by Nokia808** [comment]
@angsch 
@dreua 
I would like to vote for:

"inserting a blank page after/before each page of a selection (print a range of pages virtually non-duplex while your printer considers them all duplex). In this case I'd take the dimensions for each blank page from their respective previous/following page. If people want just one page, they can undo and will learn to just select one page."

The above scenario make pdfarranger stronger in it's abilities & cover more users needs.

**Comment by jeromerobert** [comment]
@angsch I would prefer you to work on "clear pages" than "insert blank page" because:

* No need for a dialog box to enter page size
* Solve the question about what to do on multiple selection
* Solve the question about insert before or after
* Temporary file management is already done
* Duplicate page+clear page is the same as insert a blank page

We'll see if we implement the "insert blank page" feature later. The scaling feature will help to get clear ideas on how to do it well.

**Comment by jeromerobert** [comment]
Nevermind, after thinking a bit more about the scaling feature I find that my previous post might be wrong. Both are probably easy to implement.

The reason is that we should keep the current architecture (not because it's perfect, it's pragmatic choice). I summarize it here:

* Import PDF files and render them with Poppler
* Keep changes description in `PdfArranger.model`
* Keep `PdfArranger.model` history for undo/redo
* Process PDF input files and `PdfArranger.model` variable with `pikepdf` to export files

So unless I again miss something, this basically gives the following changes for both both approaches:

## Blanking existing pages

* Add a `blank` boolean to `PdfArranger.model` (i.e. a new column) to tell if a page is blank
* Modify the preview rendering to support the `blank` attribute (I don't know how to do that but this should not be that difficult).
* Modify the `pikepdf` export code to support the `blank` attribute


## Insert a blank page

First, I think it should insert after the last selected page and only insert contiguous blank pages, so it remain simple for the user.

* Add a dialog box to enter the page size (in mm) and the number of pages to insert (please no new .ui file for such a simple dialog, keep it full python ;-) ).
* Create a temporary PDF file with `pikepdf` containing the empty pages
* Import that file as if it was imported by the user (from the `model` point of view)

I don't want to have both implemented. They are too similar and I think we should limit the feature inflation to keep pdfarranger easy to maintain. I don't have any opinion on which one of both feature should be implemented. If no one has, the choice is up to the one who will implement that feature ;-).

**Comment by Nokia808** [comment]
@jeromerobert 
Excuse me, but "Blanking of existing pages" seem different from the title of this topic or I'm wrong ? "Insert a blank page" seem to be run in the scope of the title of this issue, while "Blanking existing page" seem to talk about other thing, or I'm wrong ? This issue about creating new page without previous contents ..... Just to insure this, & may I'm wrong ....

Regarding add a dialog box to enter the page size: it should be set by default to same size of selected page, while still it make possible for user to change it manually if she/he wish.

**Comment by kbengs** [comment]
> Blanking existing pages

I guess we are thinking about a action that would be called "insert empty page" but under the hood would copy a page + blank it?

**Comment by Nokia808** [comment]
@kbengs 
If as you suspected in your previous replay, then I think we are in wrong direction ! The empty page should be new without any contents, so that user can use it to add for ex, a summary after each chapter of a scientific book. It is not good idea to have other contents that blanked because even if blanked they can be detected. Only redaction make them really not detectable. I asked developer of pikepdf about redaction & he answered that pikepdf has ability to redact contents but this is a complex process ......

I think that 2nd solution "Insert a blank page" is the correct one.

**Comment by Nokia808** [comment]
@jeromerobert 
Many thanks, & Merry Christmas hoping happy new year !
