### ISSUE TITLE
Allow to customize keyboard shortcut from configuration file

### ISSUE THREAD

**Issue by klartext** [pdfarranger/pdfarranger#276]
Might be Ctrl-Shift-S.

**Comment by dreua** [comment]
> Might be Ctrl-Shift-S.

That is already in use for "Save as".
I personally like shortcuts, we just need to find one that is free ;)

**Comment by jeromerobert** [comment]
@dreua I think we'll never find an agreement about shortcut ;-). You like it and I prefer the standard Gnome approach (shortcut only for most used features). The reasons why I think Gnome guidelines are good for shortcuts:
- shortcuts for rarelly used feature are useless as you can still access them with menu shortcut. For split page it's F10, E, S (local dependent).
- It increase the risk to have an application shortcut in conflict with a desktop shortcut

So I suggest we let the users choose their shortcuts. I'll put my veto on a GUI that allow to edit shortcut (I'm sure someone will ask for it ;-), that's too much work for little interest.  But I think that moving shortcut definition to the configuration file would be an acceptable solution. Only power users will accept to edit that file but I think that only power users ask for custom shortcuts.

This would be very easy to implement. We just need to move https://github.com/pdfarranger/pdfarranger/blob/7b5dcc0/pdfarranger/pdfarranger.py#L431-L451 to the configuration file (https://github.com/pdfarranger/pdfarranger/blob/7b5dcc0/pdfarranger/pdfarranger.py#L208). Currently the configuration file is in the `.cache` folder because it contains only stuff without much interest. If we implement this feature we'll have to move it to the `.config` folder.

**Comment by dreua** [comment]
> @dreua I think we'll never find an agreement about shortcut ;-)

@jeromerobert I guess you're right ;) But I really do like your idea to make them file-editable and I'm absolutely with you on the no to Shortcuts-GUI.


(Just had an idea for the actual shortcut: One could use plain s for split, like we use plain c for crop.)

**Comment by klartext** [comment]
> > Might be Ctrl-Shift-S.
> 
> That is already in use for "Save as".
> I personally like shortcuts, we just need to find one that is free ;)

Well, AFAIK there is a difference between "s" and "S".
Or does gtk not allow to differentiate between Ctrl-s and Ctrl-S ?

**Comment by jeromerobert** [comment]
@klartext shortcuts are defined with keys not with characters so there is not difference between ctrl-s and ctrl-S

**Comment by jeromerobert** [comment]
We should add this URL as a comment to the configuration file: https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gdk/keynames.txt
It contains the list of valid string for shortcuts. Unless I missed something this list is not available in the GTK/GDK documentation.

**Comment by klartext** [comment]
> @klartext shortcuts are defined with keys not with characters so there is not difference between ctrl-s and ctrl-S

Yes, keys.

Ctrl-Key + "s"-Key
or
Ctrl-Key + "s"-key + Shift-key

**Comment by dreua** [comment]
Still, both are taken:
Ctrl+s: Save
Shift+Ctrl+s or Ctrl+Shift+s: Save as

**Comment by angsch** [comment]
A possible solution to customized shortcuts is through accelerator maps: https://developer.gnome.org/pygtk/stable/class-gtkaccelmap.html. gedit, for example, uses this.
