### ISSUE TITLE
Does not start due to unsupported locale

### ISSUE THREAD

**Issue by jaypi95** [pdfarranger/pdfarranger#304]
When trying to start the application it outputs the following error to the console:

```
Traceback (most recent call last):
  File "/usr/bin/pdfarranger", line 33, in <module>
    sys.exit(load_entry_point('pdfarranger==1.6.2', 'console_scripts', 'pdfarranger')())
  File "/usr/bin/pdfarranger", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/pdfarranger/pdfarranger.py", line 58, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
I use Manjaro KDE with the language set to English (US) but the formats set to German (Switzerland). 

Can I fix this another way except changing the formats to US? I would rather not do that if possible.

**Comment by jaypi95** [comment]
Can confirm that it works when locale is set to English (US)

**Comment by dreua** [comment]
Discussion on the locale issue: #196 
Similar issue: #193 

As a simple workaround try running pdfarranger from the command line via `LC_ALL="en_US" pdfarranger`

Could you post the output of `locale`?

**Comment by jaypi95** [comment]
Sorry I didn't find issue #196 when I was looking for a solution.

The workaround has no effect unfortunately.

My output is
`
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_CH.UTF-8
LC_CTYPE="en_CH.UTF-8"
LC_NUMERIC="en_CH.UTF-8"
LC_TIME="en_CH.UTF-8"
LC_COLLATE="en_CH.UTF-8"
LC_MONETARY="en_CH.UTF-8"
LC_MESSAGES="en_CH.UTF-8"
LC_PAPER="en_CH.UTF-8"
LC_NAME="en_CH.UTF-8"
LC_ADDRESS="en_CH.UTF-8"
LC_TELEPHONE="en_CH.UTF-8"
LC_MEASUREMENT="en_CH.UTF-8"
LC_IDENTIFICATION="en_CH.UTF-8"
LC_ALL=
`
I don't know why exactly LC_ALL= isn't set and why the rest is set to en_CH since everything in KDE settings displays as de_CH except for display language which is en_US.

**Comment by dreua** [comment]
Similar to #196 I think this is a messed up locale, probably a bug in KDE. (Even the locale command itself is spitting errors, there will probably be more commands or programs having issues with this.)

In my Fedora+Gnome the same setting via GUI just works and results in this locale:
```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_CH.UTF-8
LC_TIME=de_CH.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_CH.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_CH.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=de_CH.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
Note that it uses de_CH instead of en_CH which seems like a more reasonable choice given that English is not one of Switzerland's official languages. (fr_CH, it_CH and wae_CH are also available on my system.) LC_ALL being empty is fine.

If you want to try my configuration, prefix each line with `export` and put it in your .bashrc or just paste it to command line for one time use. You can check your available locales via `locale -a`, I bet it doesn't contain en_CH but de_CH should be available. (You may need to install another package or do some configuration, should be easy to find on the web.)

### Workaround
I don't get why my workaround doesn't do it for you since it works for me even after exporting your locale settings but I can't really debug this any further. As a more brute workaround and given root access you could just remove the setlocale line from pdfarranger. `File "/usr/lib/python3.8/site-packages/pdfarranger/pdfarranger.py", line 58`

### Handling in pdfarranger
I'd really appreciate if someone could fix this at the source (KDE's locale selection I think) but until then I'd say we just do it like everyone else and go with a try/except, print a warning message if setlocale fails and be done with it.

**Comment by jaypi95** [comment]
Alright I removed the setlocale line and everything is working now. Thank you very much for your help and your work on this great little tool.
