### ISSUE TITLE
Let a user define a custom action sequence

### ISSUE THREAD

**Issue by angsch** [pdfarranger/pdfarranger#324]
There are several feature requests for introducing a single action for functionality that at present can be achieved by a series of actions. Examples include #236, #306. Other examples:

- I scanned a book and split the double pages into single pages. Since the skew from scanning is different for odd and even pages, I apply two distinct crop actions, on for odd and one for even pages.
- I prepare slides for hand-written annotations and add blank pages as every other page.

I propose to introduce an action that is up to the user to be filled with meaning. This custom action can cover a series of actions. This could be achieved by recording actions and then replaying them.

An issue is obviously that actions defined on one document do not necessarily make sense on another document. This includes for example pages ranges defined by a rubberband selection. However, I think that all actions defined in the hamburger/context menu are generic and can be used in a record/replay procedure. Even if restricted to these actions, quite a lot of the use cases should be covered.

**Comment by jeromerobert** [comment]
To be honest I really dislike this idea. You are trying to substitute a GUI to a CLI or an API. Many have tried before and always failed (not because it does not work but because it's a waste of energy). MS Office users always end in learning Visual Basic because macro recording is not enough. FreeCAD users always end in learning python. pdfarranger doesn't make sense if it doesn't stay simple and visual. There are already many apps to manage complex scenarios in PDFs.
