### ISSUE TITLE
Portable Mode (Windows)

### ISSUE THREAD

**Issue by smaragdus** [pdfarranger/pdfarranger#402]
As of [version](https://github.com/pdfarranger/pdfarranger/releases) [1.7.0](https://github.com/pdfarranger/pdfarranger/releases/tag/1.7.0) [PDF Arranger](https://github.com/pdfarranger/pdfarranger) is not exactly portable as it saves its configuration file (`config.ini`) in AppData:

`C:\Users\User\AppData\Roaming\pdfarranger\config.ini`

My request- when **PDF Arranger** starts it should check whether its program folder contains the configuration file (`config.ini`) and if it is there it should use it (load data from and save data to this configuration file, not using AppData for the configuration file, but the program folder instead).

This small change would make **PDF Arranger** truly portable (not writing outside its own folder) and I suppose that this feature will not be hard to be implemented.

**Comment by dreua** [comment]
The program folder would be which exactly? The folder containing pdfarranger.py?

**Comment by smaragdus** [comment]
@dreua 

I should have been more clear and specific I guess- by program folder I mean the one which contains the executable- `pdfarranger.exe`, the `dlls` and the two subfolders- `lib` and `share`. In short- when **PDF Arranger** starts it checks this folder (the one containing the executable- `pdfarranger.exe`) for the configuration file- `config.ini`, and if it is to be found there it is used. Even shorter- if `config.ini` is present in program folder it triggers portable mode- the configuration file is not saved in AppData but in program folder only.

Regards

**Comment by jeromerobert** [comment]
It sounds good, but let's wrap it in an `if os.name == 'nt':` because it doesn't have much interest elsewhere than on Windows.

**Comment by smaragdus** [comment]
@jeromerobert 

Yes, I forgot to say that I meant portable mode on Windows OS.

**Comment by GitHubRulesOK** [comment]
> It sounds good, but let's wrap it in an `if os.name == 'nt':` because it doesn't have much interest elsewhere than on Windows.

Consider Parallels/Wine/WLS users in dual mode and I have no clue what os.name reactos uses ?

Its common to include portable.dat or other flaglet in an executable directory to signal data files are stored locally e.g. not relative to "home" or "usr" having config.ini local seems to be adequate enough signal.

**Comment by dreua** [comment]
@jeromerobert I think @GitHubRulesOK hasa point here. Why do you think limiting this function to os.name == 'nt' would be necessary? Maybe it's really fine to just check for this file in any case.

**Comment by jeromerobert** [comment]
`os.name` is not related to the host operating system but to the python interpreter. So far the only Windows distribution of PDF Arranger is the one I build and it has `os.name == 'nt'` wherever it runs.

As far as I know the only Windows Python interpreter which may have `os.name != 'nt'` is Cygwin/MSYS and it is already *portable* because it provides ways to store configuration file wherever you wants. Anyway I don't expect anyone bored enough to run PDF Arranger in Cygwin/MSYS.

Storing configuration within the application folder will be concidered as dirty everywhere else than on Windows.

**Comment by dreua** [comment]
> Storing configuration within the application folder will be concidered as dirty everywhere else than on Windows.

I agree. However, we are not actively writing to this directory, just checking if a file exists there and using it in case it does. I don't see how that would be a problem on any OS but maybe I'm missing something?

**Comment by GitHubRulesOK** [comment]
Dirty Windows 🤣 
I see through them daily

**Comment by jeromerobert** [comment]
> However, we are not actively writing to this directory

I think we do. Quoting smaragdus: *if `config.ini` is present in program folder it triggers portable mode- the configuration file is not saved in AppData but in program folder only*. I think he is right, that's what *portable* mode users will expect.

**Comment by dreua** [comment]
Correction to my statement: We are not actively creating ini files in the application directory. If someone else deliberately did so, we are writing to it, that is true. I'd consider this an acceptable edge case, but if you are more comfortable limiting this to `os.name == 'nt'` that is fine with me, let's do this!

**Comment by dreua** [comment]
I just created a new label and this issue is the first to test it: I think this issue is a good starter, well defined and a reasonable addition to PDF Arranger. Unfortunately I'm not interested in implementing it myself because I would not benefit from it and my time is limited. I would, however, give guidance to new contributors interested in implementing and testing this. (The automated exe builds will make the latter quite simple, even for beginners, thanks Jerome!)

(This does not mean that "old" contributors should avoid implementing and closing this, of course.)

**Comment by midaspt** [comment]
Excuse for being late to this discussion, but as a long time user of portable Windows software, is my opinion that **PDFArranger** cannot call itself portable on Windows if it writes settings to '_%APPDATA%_'.

The current version available is misleadingly labelled "_**Portable**_" when it's simply a _**no-installer**_ package.

Case in point, should a user extract that version to a USB drive, run the program on computer A, then close it and move it to computer B, all previous settings will be unavailable, as they would have been left behind -- which makes it pointless to even write them.

If there's a problem with writing anything to the program folder, a viable alternative would be to write settings to a custom sub-folder (e.g., `conf` or `portable`), whose presence would then trigger the proper portable mode.

**Comment by GitHubRulesOK** [comment]
@midaspt the norm in such cases is  either edit the source to suit different usage or much simpler mod start to something like

set "APPDATA=x:\python stick\app\app name" & start x:\python stick\python.exe  PDFArranger.py

but that means every other onboard roaming\app is compromised until that command exits

**Comment by midaspt** [comment]
@GitHubRulesOK: The issue here is **PDFArranger** is distributed with a pre-compiled executable, as is normal with Windows programs -- not in a _py_ file that is invoked as a parameter passed to the **Python** executable -- so those solutions don't really apply.

Moreover, most Windows user are not at all accustomed to such a way of running programs; one usually just runs whatever executable the program is contained in.

Mind you, it would be no big trouble to pass CLI parameters to an executable to make it truly portable, which could be easily done with a batch file, for instance...

**Comment by kbengs** [comment]
@smaragdus @midaspt The build found here should work as suggested:
https://github.com/pdfarranger/pdfarranger/actions/runs/1472128899

**Comment by kbengs** [comment]
The issue should close automatically if/when the PR gets merged, so just leave it open.
The fix should be included in 1.8.1 which I think will be release not too far in the future.

**Comment by midaspt** [comment]
> The build found here should work as suggested: <https://github.com/pdfarranger/pdfarranger/actions/runs/1472128899>.

Can confirm, tried it without getting any visible unwanted artifacts in '_%APPDATA%_'.

**Comment by jeromerobert** [comment]
@kbengs thank you. Just 2 remarks/questions about your PR (I write here rather than in the PR because it should be of interest to all those who participate in this issue.).

- `os.path.isfile('./config.ini')` means that we look for config.ini the folder from which `pdfarranger.exe` was run. This is not always the folder which contains `pdfarranger.exe`. It means that depending on the way the user run `pdfarranger.exe`, the "portable mode" will be enabled or not. Is that expected ?

- On my pro laptop I always install PDF Arranger portable because I don't have right to install the msi. Yet I want to keep `config.ini` in `%APPDATA%`. I think I'm not the only one in that cas (this is the "no-installer" usage midaspt write about). With your PR I'll be able to do that by manually removing the empty `config.ini` after each new installation of pdfarranger. Am I right ?

As this is behavior change I think it should be in 1.9.0 and not 1.8.1, so I would prefer to keep that PR on hold until 1.8.1 is released.

**Comment by jeromerobert** [comment]
To clarify... I think we need both "no-install" and "portable" mode. The default behavior of the zip will be either "no-install", either "portable" (I guess we can't have both). With your PR we'll have the "portable" mode by default. To switch to the "no-install" mode the user will just have to delete the `config.ini` file.

It's fine with me (as a user), but I wonder if this is a common behavior among Windows applications.

**Comment by GitHubRulesOK** [comment]
In portable circles and I have been using them since the 1960's when they were in ones back pocket, the aim is to leave no footprint on the device (even if windows prefetch and reg mui is recording their usage)
To be portable the data travels on a stick with the application. There is no such thing as stealth.

**Comment by kbengs** [comment]
Remark 1: Good point, I think that would be unexpected. I think we should always check if `config.ini` is found in same folder as `pdfarranger.exe`. I'll try to modify it that way.

Remark 2: We could mention in `README.md` that it is possible to store `config.ini` in `%APPDATA%` by simply removing `config.ini` in the zip file. What do you think about that?

**Comment by midaspt** [comment]
> Remark 2: We could mention in `README.md` that it is possible to store `config.ini` in `%APPDATA%` by simply removing `config.ini` in the zip file. What do you think about that?

FYI, this is the normal behavior of most Windows portable apps.

**Comment by GitHubRulesOK** [comment]
Hmmm I was pleased to download win32.zip artifact however on run it says it wont work on my win32 suggesting I need to install Windows 64 on this 32 bit machine !

**Comment by dreua** [comment]
C'mon 32bit windows is an extreme edge case by now, just reinstall in 64 bits and move on

**Comment by GitHubRulesOK** [comment]
@dreua I can install in millliseconds on 64bits in sandbox no need for portable
I only need portable for older 32 machines that dont have a sandbox

**Comment by jeromerobert** [comment]
I will not work on a 32-bit Windows version, but contributions are welcome.

**Comment by GitHubRulesOK** [comment]
I respectfully suggest the build be tagged Win64 to reduce user expectations

**Comment by jeromerobert** [comment]
https://stackoverflow.com/questions/61776207/where-does-win32-come-from-when-im-using-windows-64bit
