### ISSUE TITLE
flatpak: Can't drag and drop a network file to the editing window

### ISSUE THREAD

**Issue by dtrossiter** [pdfarranger/pdfarranger#403]
v.1.7.0 flatpak, linux mint 20.04.
Dragging a file from a mounted network share to the editing window has no effect. Works if the file is first moved to the local machine and then dragged to the edit window. The same goes for saving the edited results. The file can only be saved to the local machine.

**Comment by dreua** [comment]
This is a limitation of the flatpak build, see https://github.com/flathub/com.github.jeromerobert.pdfarranger/issues/13

Can you give me an example of a flatpak where this is no issue? Ideally Gtk based.

**Comment by dreua** [comment]
I gave it a quick try and we can get the basic open/save operations working for the whole file system by replacing FileChooserDialog with FileChooserNative. The latter already implements the portals for us.

Unfortunately the portal-approach is not entirely transparent to the application and it [breaks some stuff](https://github.com/flathub/com.github.jeromerobert.pdfarranger/pull/15#issuecomment-770267030) we'd need to fix in pdfarranger. I don't know about Drag and Drop - it could be somewhere between  "2 line fix" and "nearly undoable".

I can offer guidance/assistance but I will not spend my free time on this because I'd rather get away from flatpak-ing than more into it.

**Comment by dtrossiter** [comment]
I installed from the unofficial PPA. Works fine, but is v.1.6.x.

David Rossiter
Sequin, WA USA

**Comment by dreua** [comment]
Please understand that we are not affiliated with that ppa. Please ask the ppa maintainer for updates or consider rolling your own.

**Comment by dreua** [comment]
I just found an easier workaround by accident: Building the flatpak with `--filesystem=host` instead of `--filesystem=home` should fix @dtrossiter issue without adding more work. I guess that home as been chosen over host by the original recipe author to limit the access to a "minimum" but seeing how many flatpaks have full host access I think that would be a reasonable change. For me personally I don't see a big difference between an app which could possibly mess with my entire `home` and an app that could mess with the whole filesystem. I won't run it as root so it can't access the interesting stuff any easier than before.

@dtrossiter shall I create a test build so you can verify that this actually fixes your issue?
@pdfarranger core contributors: This is probably no big issue but I'd appreciate a second pair of eyes anyway: Leave me a thumbs up if you think my reasoning is valid and we're good to go with `--filesystem=host`, comment otherwise.

**Flathub Statistics**
- 240 code results for [Search · org:flathub filesystem=host](https://github.com/search?q=org%3Aflathub+filesystem%3Dhost&type=code) (21 limited to read only)
- 253 code results for [Search · org:flathub "filesystem=home"](https://github.com/search?p=26&q=org%3Aflathub+%22filesystem%3Dhome%22&type=Code) (20 limited to read only)
- 4 recipes define both :shrug: [Search · org:flathub "filesystem=home" "filesystem=host"](https://github.com/search?q=org%3Aflathub+%22filesystem%3Dhome%22+%22filesystem%3Dhost%22&type=Code)

**Comment by dreua** [comment]
[Sandbox Permissions — Flatpak documentation](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access)

**Comment by jeromerobert** [comment]
@dreua Thank for that really exhaustive post. PDFMixTool, Meld and KWrite use `--filesystem=host` so I guess you are right, pdfarranger should do the same. Moreover `--filesystem=host` is still very limited and an app still cannot mess the filesystem.

**Comment by dtrossiter** [comment]
Yes on the test build. Happy to test it. Would it be a somewhat traditional
flatpak install?

*Best, David*
_______________________
Sequim, WA 98382

*~~~ Americans should wear masks in all indoor public spaces ~~~  *
#WearAMaskWA

**Comment by dreua** [comment]
@dtrossiter Here you go. Could you also try an external drive / USB stick while you are at it? Thanks!

> Build [38337 successful](https://flathub.org/builds/#/builders/32/builds/38337)
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/36921/com.github.jeromerobert.pdfarranger.flatpakref
> ```

**Comment by dtrossiter** [comment]
All works well now. I'm able to edit files from my local Home folder,
network mounts and USB thumb drives. Thanks for the fix!

*Best, David*
_______________________
Sequim, WA 98382

*~~~ Americans should wear masks in all indoor public spaces ~~~  *
#WearAMaskWA

**Comment by dreua** [comment]
I merged the change into master, that means it should appear on flathub in one or two days, but flathub does not show that unfortunately. 
@dtrossiter the install from testing repository works for now but I don't think that it will get updated ever. Don't forget to uninstall it and install from flathub again for automatic updates.
