### ISSUE TITLE
Segmentation fault if "crop white borders" while rendering thumbnails

### ISSUE THREAD

**Issue by kbengs** [pdfarranger/pdfarranger#405]
Steps to reproduce:
* Open a large pdf
* Select a page a choose "crop white borders"

App will close with Segmentation fault.
page.render(cr) in croputils conflicts with page.render(cr) in rendering thread

**Comment by jeromerobert** [comment]
I can think of 3 solutions:
* Add a lock to each page (in the `Page` class) so *crop white borders* wait until rendering is finished to do it's own rendering. Unfortunately, I guess it will freeze the GUI until the rendering is finished.
* Disable *crop white borders* during the rendering. This is probably not good because the user will not understand why this action is grey out.
* Create a dedicated `Poppler.Document` instance in *crop white borders* (It should work according to https://gitlab.freedesktop.org/poppler/poppler/-/issues/666)

So unless someone have a better idea I will go with the third one.

**Comment by jeromerobert** [comment]
Well actually, locking the `Poppler.Document` instance work nicely.
