### ISSUE TITLE
Scanner integration

### ISSUE THREAD

**Issue by hubertmeier** [pdfarranger/pdfarranger#423]
Hi,
this is a great project. Would you consider to integrate a scanner dialog (Twain, WIA, Sane) to import pictures from a scanner? 

Thank you

**Comment by dreua** [comment]
Not sure about the other contributors but I don't own a scanner so I won't work on such a feature. If anyone does it with reasonable or optional dependencies and good UI integration I'm not against it though. (I'll try to help where I can but I won't implement it myself.)

Let's see whether something productive comes up, otherwise I'll close this in about 3 weeks. Anyway, thank you for the praise and the idea :smile: )

**Comment by jeromerobert** [comment]
Even if we ignore the volume of work and new dependencies I would also vote for a closure. Sane/Twain is producing bitmaps so it is a good input for Gimp, not for PDF Arranger.

**Comment by dreua** [comment]
Closing this as announced.
Just FYI: There are scan applications on Linux. Paperwork looks nice for the special use case of scanning for archival+ocr. Pdfarranger can make PDFs from its jpegs (The included PDF export should be improved...).

It should also be possible to scan with scanimage and start pdfarranger with the scanned files via bash. I'd try that depending on the use case.
