### ISSUE TITLE
Code Coverage / Dogtail tests

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#455]
I had a quick look at the Coverage reports and I wonder what our goal should be and whether adding tests could be a mandatory requirement for PRs adding features and maybe if we should ask for help with creating tests more actively on the issue tracker.

Is full coverage a reasonable goal here?

I noticed that the code paths for password protected PDFs aren't tested at all, maybe that would be a good place to start? Should I create separate issues for stuff like that?

**Comment by angsch** [comment]
Many of the issues like the page rotation bug or the additional margins were found by visual inspection of the output PDF. I don't see tests catching these issues. What I would find useful is to collate a set of PDFs that have revealed issues in the past. I assume that we all have our private collection, but potential new contributors have not.

Personally, I see the potential of tests more in catching issues arising from dependencies. Think of all supported versions of pikepdf on various platforms.

**Comment by jeromerobert** [comment]
> Is full coverage a reasonable goal here?

If yes, I don't know how. What is mostly missing are tests of mouse interactions like drag and drop or selection with rectangle. I don't know yet how to do that in way that it keep tests maintainable (ex: resiliant to small UI changes).

> I noticed that the code paths for password protected PDFs aren't tested at all, maybe that would be a good place to start?

Yes ! It should be easy. I can work on that.

> Should I create separate issues for stuff like that?

I would say we could trac it here for now.

> Many of the issues like the page rotation bug or the additional margins were found by visual inspection of the output PDF. I don't see tests catching these issues.

Exactly. Currently tests mostly check that the UI do not crash. We would need a way to export the current page display to an image and compare it to a reference. The problem is to do it in a way that does not depend on the style of the display because we don't want to regenerate all reference when changing the version of Gtk (for example). So this cannot be a simple screen capture.

> What I would find useful is to collate a set of PDFs that have revealed issues in the past

It should be quite easy to collect all PDFs from this issue tracker using the Github API. But how would you use this collection in concrete terms?

> That said, testing at the function level would be pretty difficult (or at least cumbersome) given that the code dealing with operations on pdfs is not well separated from the GUI.

Exactly. I would go this way only if we have some functions that are complex enough to be tested independantly and if we do not manage to implement image comparisons.

**Comment by dreua** [comment]
I think OpenQA has functions to check for specific needles in a screen capture. But it would probably unreasonable to set up an instance just for PDF Arranger. Maybe we could ask some linux distribution if we could use theirs...

**Comment by dreua** [comment]
PDFs could maybe also be reused from pikepdf or qpdf as they have similar testing issues in that regard.
