### ISSUE TITLE
Idea: More modularity

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#474]
I just got a quick idea which I wanted to share with you:

### Problem
Adding more and more features can lead to a cluttered code base and may become hard to maintain in the long term. I sometimes feel reluctant to add too many new features because I have this in the back of my mind.

### Solutions
Many programs, most notably editors like Gedit, Notepad++, VS Code, Eclipse but also Browsers like Firefox and Chrome, solve this problem by having a plugin system to extend functionality. This is not what I want for PDF Arranger, at least not in the near future.

My idea is, however, to design "Plugin-Like" features a bit more like plugins and remove some of the "monolith" feeling I get when opening pdfarranger.py. In practice this could mean, that each feature gets its own file and would use some kind of internal API. We would still have all code in one place and could change that API at any time, but we'd need to update the features using it as well.

(One could also say: Let's use more object oriented programming and improve our architecture :wink: )

Examples for issues which could be implemented in this way: #471 #438 #346 #327 #246

**Comment by GitHubRulesOK** [comment]
The concept of "plugins" is to lock and load at start up 
This thus causes a resource hog which is why some notable plugin biased apps often require two sets i.e.
Acrobat has two plugin folders and other have an "as required" secondary folder.

The simples approach I adopt elswhere is to have a lightweight non active / non interactive user listing of on demand "addin" features such as cpdf, mutool or qpdf for their extra functions such as N-up or masking or line thickening or poster OR any other command line ability. The gotcha is releasing file locking temporarily or working via a temp copy and replace current target.

Thus the interface is minimal as the command line calls most simply need to pass the selected filenames and page ranges etc.

**Comment by logari81** [comment]
My personal approach is to do few things and try do them well. I believe, delivering high quality super polished software is more boring but it is what can make the difference in terms of the open source software "branding". I have in the past participated in a software project very much relying on a plugin system and you end up with some super polished parts and other parts that are less polished.
