### ISSUE TITLE
IconView is within a scrolledwindow. Can we get rid of the latter?

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#506]
Trying to fix #501 I discovered a few issues with the above mentioned chaining:

- `self.iconview.get_visible_range()` always returns the whole range of pages, no matter what is actually visible to the user
- `self.iconview.scroll_to_path(self.iconview.get_selected_items()[0], True, 0.5, 0.5)` doesn't do anything, probably because it thinks that everything is already visible

As I understand [Gtk.IconView's documentation](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/IconView.html), it already is derived from a Gtk.scrollable, therfore putting it inside a scrolledwindow should not be necessary. Is anyone aware of reasons we need this? Can we refactor it to get better scrolling UX for #501 and possibly other use cases?

**Comment by kbengs** [comment]
I have experimented with this. The reason it does not work is because we have a viewport.
```
-        self.sw.add_with_viewport(self.iconview)
+        self.sw.add(self.iconview)
```
That will make the functions work. It will also fix #505. But there are a few other things that need to be fixed if we do that change. For instance drag-and-drop will not work because the coordinate system is wrong.

One thing that the change will break is the code that allows a drag-select to be started from left margin at the same time as the margin above first row is small... (d2c8d75). I haven't found another way to fix that.

I could have a new look at this but I think it will not be in the near future.
