### ISSUE TITLE
Question: Options to compress PDF exported files

### ISSUE THREAD

**Issue by mruncleleon** [pdfarranger/pdfarranger#523]
Hi all, first thanks so much for this software.

Any chances in roadmap to add options for compression?

**Comment by jeromerobert** [comment]
Could you elaborate ? Do you mean recompress the jpeg images which are included in the PDF file to a lower quality ?

**Comment by mruncleleon** [comment]
Yes or to change DPI from 600 to 100 to reduce resolution in exported file

**Comment by homocomputeris** [comment]
@mruncleleon For now, to do this you can use [Ghostscript](https://blog.rot13.org/2011/05/optimize-pdf-file-size-using-ghostscript.html) or [OcrMyPdf](https://ocrmypdf.readthedocs.io/en/latest/cookbook.html?highlight=optimize#pdf-optimization), which is also based on pikepdf by jbarlow83.

**Comment by jeromerobert** [comment]
We often have request to plug existing tool CLI tool features in PDF Arranger. It's not the spirit of PDF Arranger. The reason why I forked pdfshuffler, is to have a tool to **see** pages while moving them. As far as I know this feature is not available in other open source PDF tools. PDF Arranger is not and won't be a GUI for OcrMyPdf, Ghostscript, pdfTk, qpdf, ... and all very good open source PDF tools.

This being said, It should be pretty easy to add a way to run any external program from PDF Arranger:

* Save selected pages to a temporary PDF file
* Run the external tool which read and modify that file
* Wait for that tool to exit
* Import the temporary PDF file, replacing the selected pages (assuming that the modified PDF file have exactly the same number of pages, in the very same order).

Each external tool could be declared in the `config.ini` file (where keyboard shortcuts are already). They could be available in a dedicated menu named like *External tools*. Of course those tools won't have any dedicated dialog/GUI.

Unfortunnalty, I guess that people who are handy enough to figure out how to declare external tools in `config.ini` are also those who do not care about using a terminal to run that tool.

Tell me if I am wrong !

**Comment by homocomputeris** [comment]
There is definitely no need to support all those tools (or other not mentioned ones), as pikepdf [seems to be capable of handling size reduction more or less by itself](https://github.com/jbarlow83/OCRmyPDF/blob/master/src/ocrmypdf/optimize.py).

Anyway, in Linux one can always pipe a PDF to GS.

**Comment by jeromerobert** [comment]
Your link shows that pikepdf **is not** able to handle size reduction by itself. It can replace images by others but additionnal dependencies are need to reduce images size.

Also note that GS is doing image scaling while OcrMyPdf is doing recompression or color change but not scaling. For a scanned 2 colors (black/white) PDF I guess that OcrMyPdf will not reduce size while GS will. So having both is usefull.

We could do image scaling without adding additionnal dependencies because we already depends on PIL but I would prefer the "external tool" way.

**Comment by mruncleleon** [comment]
Thanks guys. I saw 2 suggestions that are PDFknife and pdfminify to handle other operations beyond scope from PDFArranger but i dont have knowledge with programming languages.

**Comment by mruncleleon** [comment]
@homocomputeris sorry, i forgot to inform that i'm in Windows OS.

**Comment by zareami10** [comment]
I would also really like to see this option.

I often simply drag-drop various images/scanned files to pdfarranger to create PDFs to send over email and such, so having a simple 'optimize' option (similar to Adobe Acrobat for example, which does both scaling and various other operations to reduce size) would make sure I will get reasonable sizes without a lot of tweaks or external tools.

Although this indeed may entail more dependencies unfortunately.

**Comment by jeromerobert** [comment]
> @homocomputeris sorry, i forgot to inform that i'm in Windows OS.

Even if we gave the possibility to call OcrMyPDF or Ghostscript from PDF Arranger, it is clear that I would not include these tools in the Windows distribution of PDF Arranger. So you would have to install them yourself. And once installed, you would probably be able to use them without PDF Arranger.

**Comment by mruncleleon** [comment]
So pdfknife or pdfminify is out of the question in this project? I need to learn python right now lol

**Comment by jeromerobert** [comment]
Closing. Too much effort for small benefits as many tools already exists for that.

**Comment by mara004** [comment]
> PDF Arranger is not and won't be a GUI for OcrMyPdf [...]

From my point of view, integrating OCRmyPDF could be worth being considered as possible long-term goal, since it also has a Python API and to my knowledge there is no (open-source) ocrmypdf gui yet...

**Comment by bidinou** [comment]
Hi ! Thanks a lot for maintaining this IMHO essential piece of software :)

Just reducing the signal to noise ratio to say that such a feature (re-compressing / reducing the resolution) would be very useful for "average users". 

Yep indeed, my family, wife and even disabled people at work use Linux (KDE Neon mostly) and this additional step (resorting to an another piece of software / to the shell) is just out of reach for them - contrary to the general use of the system :-) 

Just my 2 "spoiled kid" cents :-) 
cheers & thanks again !

**Comment by dreua** [comment]
@bidinou There is a GUI for ocrmypdf, maybe that could be a workaround? [digidigital/OCRthyPDF-Essentials (A GUI for OCRmyPDF)](https://github.com/digidigital/OCRthyPDF-Essentials) (I might consider packaging it for Fedora or Flathub in case that would be requested.)

I really do not want to raise false expectations but this is in fact currently the most requested feature: It's the issue with the most  [comments](https://github.com/pdfarranger/pdfarranger/issues?q=is%3Aissue+no%3Amilestone+sort%3Acomments-desc+label%3Afeature) and it's sharing the first place by [number of :+1:](https://github.com/pdfarranger/pdfarranger/issues?q=sort%3Areactions-%2B1-desc+is%3Aissue+no%3Amilestone) with one other issue. I do admit that two :+1: and the number of comments alone is not that statistically significant, though.
Nevertheless, I believe that there is real interest in this feature and therefore we should not stand in its way: I won't have the time to work on this myself, but I think we should consider accepting a PR implementing it in a sustainable and maintainable way. (Maybe optional / no Windows support?)

**Comment by KraXen72** [comment]
i think this would be a great addition to pdfarranger, since i don't want to upload my pdfs to some shady online compression services. Although, i understand if it's out of scope.

**Comment by dreua** [comment]
There are command line tools for Linux which should also work with wsl on Windows for this task, you are not forced to use online services for this. Can't give recommendations though as I haven't used those myself. Depending on the case hosting the file on next cloud etc and sending a link might be the easiest and best solution.

Please let me know if anyone wants to work on this or has experience with other open source tools for this task.

**Comment by glocalglocal** [comment]
This would streamline the workflow of working with one or more PDFs, and give average users a GUI way to use Ghostscript. As far as I am aware, there is no Ghostscript GUI, and using CLI commands is scary at least for average and point-and-click  Windows users (ie the vast majority of them). 

As a Windows user trying to move to Linux, the absence of an integrated PDF editing tool that is comparable to Acrobat Pro is one of the reasons stopping me. PDF Arranger is closer to that integrated tool than most -- and I think I tried all of them.

**Comment by article10** [comment]
It would indeed be great if there was some way to reduce the filesize on export with PDF Arranger.

I had it merge a number of .pdf files generated with Microsoft Word (so they're text documents) and some website printouts (generated with Microsoft print to PDF and Chome's built in Save as PDF feature), and the combined size of the file generated with PDF Arranger (200+ MB) was over ten times larger than all those initial Word-generated .pdf files added together. I'm not sure if that makes sense, but for most purposes such an enlarged filesize is not usable output.

The first thing I tried was to use PDF Arranger's _print_ option instead of export and then use _Microsoft Save to PDF_ as the 'printer'. This took down the filesize to around 40 MB, still too large, and OCR was lost.

I did find a solution which works on Windows.

1. Get **Ghostscript** (thanks for the suggestion @homocomputeris) which is released under AGPL. 
2. Then get **GhostFriend - GhostScript GUI** (https://www.noliturbare.com/convert.php). 
3. Select _Output file Format_: PDF. 
4. Go to _PDF Joboptions_, 
_Default_ is still too large (took down the filesize to 100MB), same for Print (40MB). 
_Screen_ made the images way too low-res. 
So in the end only the _eBook_ setting was a good compromise at around 20MB. Apparently this is 150dpi?
Click Convert to PDF and let it do its thing for a few seconds.

It maintained the OCR in the file. 

It seems GhostScript is just reducing the resolution of images in the pdf without trying (or offering the option of) more efficient compression first.

PDFknife seems to just use Ghostscript as well by the way: https://github.com/sciunto-org/PDFknife/blob/master/PDFknife/shrink.py

So I think trying actual compression (not just downsampling) of the images in the file would be more elegant. 

If **OCRMyPDF** is to be used to optimize, the user must choose between lossless (e.g. --optimize 1) and lossy (optimize 2 / optimize 3)  (https://ocrmypdf.readthedocs.io/en/latest/cookbook.html#pdf-optimization). 
But it's a hassle to install OCRMyPDF on Windows so I won't be able to test it. 

**pdfminify** also seems to offer the option of compression without simply downscaling image resolution, but again there's no easy way for the average user to run it on Windows.

Since it's the most requested feature but it's actually already provided by seperate open source tools, I suppose it'd be possible to create a button in PDF Arranger that runs some PowerShell scripts (for OCRMyPDF https://marko.euptera.com/posts/ocrmypdf-windows.html), and a checkbox which can then be checked in PDF Arranger that then applies OCRMyPDF optimization on PDF Arranger's output file (with the defaults being set to lossless to not needlessly destroy quality), or alternatively applies pdfminify.

**Comment by dreua** [comment]
@article10 if the output of PDF Arranger is actually significantly bigger than the sum of its inputs that would be unexpected. If you can share the inputs (or recreate them) please create a new issue with those.

**Comment by bittner** [comment]
Some related discussions of sister projects:

- https://github.com/pikepdf/pikepdf/issues/558
- https://github.com/qpdf/qpdf/issues/1402

I'd love to see compression integrated as an innocent option, either in the Settings or a Save As... dialog. The reduced, GNOME-style user expierence of PDF Arranger is a great asset! 😍
