### ISSUE TITLE
Add support for adding images overlay

### ISSUE THREAD

**Issue by bellegarde-c** [pdfarranger/pdfarranger#530]
This software is really cool but I'm missing one feature: a way to add my signature (PNG) to a PDF.

Not sure if it's complex and/or out of purpose.

**Comment by mara004** [comment]
An interesting idea. In theory it is possible to do this with pikepdf, but it might be difficult to integrate this feature into pdfarranger. @jberkenbilt once shared an interesting [script](https://github.com/qpdf/qpdf/issues/207#issuecomment-830702745) to apply a signature overlay to a PDF page.

However, I see some difficulties:
* PDF rotation modifies the coordinate system rather than just the page. This means that when applying overlays to rotated pages, existing rotation and the position shift would need to be compensated for.
* If the same overlay is applied to more than one page, it should not be embedded separately multiple times, since this would negatively impact performance and file size. There would need to be some elegant way to recognise same overlays and share the image data.
* The way of embedding images shown in Jay Berkenbilt's example only supports PNGs with alpha channel and does not compress the image data. It also involves a lot of low-level image to PDF conversion code.

A different approach would be to use img2pdf (the latest git master now supports alpha channels). The converted image page could then be placed as Form XObject on the target page. This solution would support more formats and compress images, but it would still be quite complex.

**Comment by AlisterH** [comment]
Page stamping is a common feature in other software, and it isn't just used for signatures, but draft stamps, logos etc.  I imagine if pdfarranger allowed stamping with a pdf overlay/underlay (like qpdf does) the feature would be well used.  In my mind it is better to leave it up to users to produce a pdf to use as a stamp, using other appropriate software, rather than implementing a gui that is either limited in terms of what it can put in a stamp, or is complicated, trying to produce every kind of stamp people might want.

**Comment by mara004** [comment]
>> PDF rotation modifies the coordinate system
>
> Yes. And there is also page scaling and truncating

When scaling pages with overlay, you simply need to scale overlay position and target size, provided that overlays are applied after scaling. I think there should be no problems with placing overlays on already scaled pages, since the coordinate system modification only applies to the scaled XObject of the page, not to the page as a whole.

> Only in the very same paste action. We don't have way to track that accross multiple paste.

You don't need to track it. You could probably get around this problem by using a dictionary-like data structure that maps from an overlay page object to a Form XObject, thus avoiding redundant resources. This would require proper `__eq__` methods on custom objects though, maybe `vars()` could help.

> Now that PikePDF have pikepdf.Page.add_overlay this should be easy

Last time I experimented with `add_overlay()` I ran into weird problems with rotated pages and ended up placing classical Form XObjects again, which might be more flexible. `add_overlay()` does not provide much advantages compared to lower-level content instructions and `contents_add()` in my opinion.

**Comment by mara004** [comment]
> Last time I experimented with add_overlay() I ran into weird problems with rotated pages and ended up placing classical Form XObjects again

Possibliy this is related to https://github.com/pikepdf/pikepdf/issues/259 ...

**Comment by kbengs** [comment]
> It shoud be implemented as a special copy/past (Paste as [overlay|underlay]) of an existing page
Past should popup a dialog box to enter the coordinate of the target rectangle on the target page. We will NOT provide any way to define that rectangle graphically.

I have this working as @jeromerobert suggested, except for the GUI part...
Imo this feature would be hard to use without any GUI. (every placement attempt will also create new temporary file(s))
So I have done something simple:
![Overlay_printscreen](https://user-images.githubusercontent.com/60842129/216752265-9ffe3d04-23f4-4664-9626-a2b3f94e1d9e.png)

The large rectangle is the "paste to" page. The grey rectangle is the copied overlay. The overlay can be dragged with mouse. When clicking OK it will create a new temporary file with the overlay on top, one for every selected page.

All code is done in overlay.py, it is currently 336 lines. :-)

I have also found out that the overlay can be used to create N-up. (create a empty page large enough to hold all pages, add the pages one at a time to the empty page)

What do you think about this GUI?

**Comment by jeromerobert** [comment]
This is great. This will be the killing feature of 1.10.
