### ISSUE TITLE
Add "Open File" Button

### ISSUE THREAD

**Issue by AvidGame** [pdfarranger/pdfarranger#581]
I have used PDFArranger for rotating the pages of few files now and the software is amazing. However, I found the import function in the program to be a bit counterintuitive especially when I am processing more than one file. Now if I want to rotate the pages of more than one file I would have to first open a new window then import the new file. Otherwise, if I were to use the import function to open another file with my current file open it would add the pages of the new file to the current one which is an unwanted behaviour for batch processing.
I think it would be best to have both options which are: **Open file** (opens new file in a new window) and **Import file** as it would make the software more user friendly.

Thank you again for your work on this software.

**Comment by hairycactus** [comment]
> Open file (opens new file in a new window)

Are you requesting for a `Open File in New Window` button -- instead of being limited to the current 2-step [`New Window` > load file] workflow ? If yes, I would like to have such a single-step function too.

A similar function was mentioned in Nov 2020, but the Devs only decided to add a new empty window function:
https://github.com/pdfarranger/pdfarranger/pull/319

Even better would be making PDF Arranger a tabbed program, but the Devs thought it was too much work:
https://github.com/pdfarranger/pdfarranger/issues/326

I suppose we have to live with a not-so-ideal multiple-window workflow for now.

**Comment by kbengs** [comment]
I agree it works a bit unusual/strange in PDF Arranger.

As files can be added several ways, (file open, dnd from another instance, dnd from a filemanager, copy-paste from another instance, copy-paste from a filemager, command line arguments), It feels a bit unclear how it should handle all these open/import cases. But maybe it isn't so hard after all. I can have a look at it and see what I can come up with.

**Comment by AvidGame** [comment]
> > Open file (opens new file in a new window)
> 
> Are you requesting for a `Open File in New Window` button -- instead of being limited to the current 2-step [`New Window` > load file] workflow ? If yes, I would like to have such a single-step function too.
> 

Yes that's exactly what I wanted! Having to open a new window and use the import function for every other PDF is very tedious. I do not want to append the documents; I just want to rotate the pages. 😁 

I don't think it is hard to implement as someone has already gone through the hassle of adding the "new window" functionality. All we need to do is call that function 
and make it open the file in a new window.
