### ISSUE TITLE
High Display Resolution Support

### ISSUE THREAD

**Issue by ScriptShape** [pdfarranger/pdfarranger#606]
I want the thumbnails to be rendered at higher resolutions on higher resolution displays.

**Comment by dreua** [comment]
Gift me a HighDPI screen and I'll do it! Jokes aside, I really think we need a developer who owns such a display to implement and test this feature. If you don't have the python skills for a PR and the other developers here don't have such screens then there is nothing that can be done here, I'm afraid.

- Let's give this 2 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.

**Comment by kbengs** [comment]
Since 1.8.0 pages can not be zoomed in as much as before. This is limited because large thumbnails will use a lot of memory. It will also be CPU heavy. The max zoom level limit could probably be made to adjust itself according to available memory. @ScriptShape do you use the latest version? If you use a older version it is possible to zoom in more but the thumbnails might not be sharp.
