### ISSUE TITLE
Separate pages into individual files.

### ISSUE THREAD

**Issue by mnwstl** [pdfarranger/pdfarranger#608]
I don't know if this is the ideal place for this message: Could there be a function to separate pages from a document into individual files?

**Comment by dreua** [comment]
Yeah, we already have that :smile:

**Comment by dreua** [comment]
I think that makes PDF Aranger feature-complete :laughing: :rocket:

**Comment by mnwstl** [comment]
I was hasty in posting this and then found no way to remove it. Sorry.

**Comment by dreua** [comment]
No worries, closing the issue is exactly right in this case. I'm happy to hear that this feature found another user. We don't really know how people are using PDF Arranger (there are no usage statistics or any calling home at all) so sometimes I wonder whether a requested feature will be used by any one except the person requesting it.
