### ISSUE TITLE
Feature: Crop to Absolute Dimensions

### ISSUE THREAD

**Issue by jcuenod** [pdfarranger/pdfarranger#635]
Periodically I receive scans that have pages of different dimensions. I would like to be able to crop them to a fixed width and height so that they are all the same but the crop tool doesn't allow you to control the width and height at the same time with absolute measures.

**Comment by jeromerobert** [comment]
This would only be possible if the ratio between the right and left, and top and bottom margins is constant for all pages (for exemple the cropped space is always in the middle of the page). Is that the case ?

**Comment by jcuenod** [comment]
Ahh, no. I think what I'm imagining is "crop to width x height" rather than "crop from width x height"—the user specifies the target width and height.

**Comment by jeromerobert** [comment]
And target width and height it not enough to define a crop. We need to know how much you want to crop on each side. If it's different for each page we cannot process all pages with a single action.

It would be possible to do absolute crop instead of relative, but with constant margins, not with constant target page size.
