### ISSUE TITLE
Actually crop / split pages instead of just setting the mediabox

### ISSUE THREAD

**Issue by w-oertl** [pdfarranger/pdfarranger#660]
After splitting a page using the split tool, multiple smaller pages replace it. When saving or exporting one or more such smaller pages in a file, the whole original page's image is written with crop instructions. All of this is surely well known to developers and most users.

However, this makes the file unnecessarily large and also may contain unwanted information. So how about actually splitting the page's image into separate smaller images, one for each result page? Thanks.

**Comment by dreua** [comment]
Yes, this is well known, the page format dialog even warns about that fact. The split function does not, but it works in a very similar way.

**Comment by dreua** [comment]
I edited the title to make it more clear what this is about. Feel free to edit again, if you come up with something better.

I agree that it would be nice to have such a feature, but I'm afraid that we are not going to implement it, because it would require us to completely parse and understand the PDF structure in order to remove the unwanted content. (Including editing of images, maybe even text blocks to remove the contents outside of the new mediabox.) I think this is a big task beyond the resources we as PDF Arranger developers can spare.
Is there any library or free software which currently supports this kind of PDF editing (without rasterization)? (I doubt it, tbh.)

**Comment by dreua** [comment]
- Let's give this 3 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.
