### ISSUE TITLE
[Flatpak/latest version] Error when save pdf

### ISSUE THREAD

**Issue by spoontex** [pdfarranger/pdfarranger#715]
Describe the bug
----------------

When I insert some tiff files to a new pdf I can't save to pdf. I get this error. 

Use pikepdf.pdf.pages interface to copy pages from one pdf to another

To Reproduce
------------

1.  Insert some files
2.  Save to PDF

![Screenshot_20220914_172109](https://user-images.githubusercontent.com/48591285/190196751-51db2dbd-6dae-4633-9109-d8649b577c25.png)

**Comment by spoontex** [comment]
Yes, I tried tif, pdf, png... any type of file. I use ver: 1.8.2.

**Comment by dreua** [comment]
So this is not specific to tiff at all? Your initial post made it sound like that.

Please go to the menu, "About" and screenshot / paste the versions of libqpdf and pikepdf. What is your operating system / Linux distribution (with version please)?

**Comment by dreua** [comment]
And how did you install PDF Arranger?

**Comment by spoontex** [comment]
Sorry about that. English is not my main language.

![Screenshot_20220914_175724](https://user-images.githubusercontent.com/48591285/190204107-00855ed5-00ce-49ee-97aa-c019d91c9377.png)

**Comment by spoontex** [comment]
I install PDF Arranger through snap.

**Comment by spoontex** [comment]
yes. flatpak. Sorry.

**Comment by dreua** [comment]
Please update to the latest flatpak version and try again. (For me that was just `flatpak update` on the command line.) I don't know the details of flatpak updates and distribution but for me it already works. It may take another hour or so for you. 
The about dialog should show libqpdf 10 instead of 11 and everything should work as expected.

Thanks again for reporting this! I pushed the update to qpdf 11 earlier today and quickly reverted it now.

**Comment by dreua** [comment]
I'll create a new issue for fixing the incompatibility with qpdf 11 / qpdf 6, this issue can be closed when PDF Arranger works again for you.

**Comment by spoontex** [comment]
Thanks.

**Comment by dreua** [comment]
Did you get the update? Does it work?

**Comment by spoontex** [comment]
Works!! Thank you very much!!
