### ISSUE TITLE
readme.md instructions for Debian

### ISSUE THREAD

**Issue by handmeatowel** [pdfarranger/pdfarranger#730]
Describe the bug
----------------

Fails to build without libqpdf-dev which is available from the distro.

The Documention should include this information.

System and Versions
-------------------

- PDF Arranger via pip3 install --user --upgrade https://github.com/pdfarranger/pdfarranger/zipball/main
- python3-pikepdf/testing 5.1.1+dfsg-1+b1 ppc64el, distro package
- Debian Bookworm, powerpc64le

**Comment by jeromerobert** [comment]
I don't think so.

If you use the distro pikepdf you don't need libqpdf-dev because pikepdf is already built. And if the debian pikepdf package needs libqpdf-dev at runtime the bug should be reported to Debian.

If you use the pip pikepdf you should not need libqpdf-dev because it embed it's own libqpdf.

If I'm wrong please show the error message so I could investigate.
