### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by mapi68** [pdfarranger/pdfarranger#736]
Missing a good installer for Windows.
I created a new installer here: https://github.com/mapi68/pdfarranger/releases

**Comment by Matth7878** [comment]
Nice. Is it still possible to install only for current user?
Without admin rights I am not sure user can install for all users. (Seems to me it is not possible but I didn't check it to make sure)

**Comment by mapi68** [comment]
Try now......
![screenshot_2022_09_26_at_06_57_02](https://user-images.githubusercontent.com/41143572/192197230-ffae3fcf-b3b2-4e51-81fd-39820aca47dd.png)

**Comment by dreua** [comment]
All I see here is an exe that could continue anything. I would not run that on my machine and I'd like you to make it very clear that this is not an official build of PDF Arranger. I have no reason to believe you have bad intentions but I don't have a trust relationship with you either, someone could have hacked your account or there could be malware on your computer which could have infected the exe... 

Jerome did almost all of the work of the official PDF Arranger installer so this will be ultimately up to him to decide. In order to consider this at all, we'd need some information on how you built this: Is it open source / which license? Will it compile on Linux? Can it be automated in our CI?

**Comment by mapi68** [comment]
![_20220926_213553](https://user-images.githubusercontent.com/41143572/192364633-483bc242-7dc4-48e8-b2ee-2b8547dc1e7b.png)

**Comment by jeromerobert** [comment]
I would gladly stop to maintain the [cxx_freeze](https://github.com/marcelotduarte/cx_Freeze) / [msilib](https://docs.python.org/3/library/msilib.html) based installer which I admit is not that beautiful.

@mapi68 But to make your work compliant with open source standards you need to make it works in a public CI, for exemple Github Action. To do that you need to fork our pdfarranger repository. Github Action have Windows. I don't known anything about MSI tools licenses.
