### ISSUE TITLE
Change modified date by default

### ISSUE THREAD

**Issue by greybit** [pdfarranger/pdfarranger#761]
Describe the bug
----------------

PDF Arranger does not change the modified date inside the document by default.

Expected behavior
-----------------

Automatic change of modified date.
If someone dont like it, they can change it back in document proberties.
However, if think that a automatic change of this is what most users would expect.

System and Versions
-------------------

-   PDF Arranger 1.9.1 on Win10 and OpenSuse Tumbleweed (rpm)

**Comment by jeromerobert** [comment]
The current logic is do not change any meta data. As you may have notice we also do not replace the *Producer* by "PDF Arranger". And no, the user cannot change it back in document properties because the original date would be lost. So unless more people vote for that change I would prefer not to do it.

However, since entering a date in ISO 8601 format by hand is not a very pleasant experience, we could add a button in the metadata to quickly set the *Modified* date to the current date.

**Comment by greybit** [comment]
I dont know the benefit of not changing the meta data. For me, as a user, i think that a change of a document should be documented. I dont understand the disadvantage of changing this. If there is one, pls feel free to explain it to me.

Instead of a button to change the "modified date" there could be a checkbox that keep the setting.

**Comment by dreua** [comment]
I really don't care about the modified date. Certainly won't be working on it but open to merging PRs changing this behavior.

- Let's give this 3 weeks. If nothing productive comes up it should be closed and tagged `stale feature`.
