### ISSUE TITLE
Printing doesn't work right - printed document is too small, doesn't fill whole page

### ISSUE THREAD

**Issue by galgogergo** [pdfarranger/pdfarranger#806]
Describe the bug
----------------

No matter what I try to print, it prints like this: 

![image](https://user-images.githubusercontent.com/121640946/210609350-31508975-788d-41c2-8b15-02db69caab42.png)
(picture cropped because of space)

It's like this even when printing through _Microsoft Print to PDF_ service.
If I check "show print preview" in the printer settings*, it looks the same there as well; I don't even need to print it physically. (but it will look the same when I do)

'* my printer is a Kyocera M3540idn

To Reproduce
------------

Try to print anything... 
It will put out something like the picture above, or the attached bad printing.pdf file. (that file I printed using the Microsoft Print to PDF service, but physically printing it resulted in a same look.)
See [bad printing.pdf](https://github.com/pdfarranger/pdfarranger/files/10345965/bad.printing.pdf)

Expected behavior
-----------------

Well, I was expecting it to print to the full page. In Acrobat it printed without problem.

Input files
-----------

Result: [bad printing.pdf](https://github.com/pdfarranger/pdfarranger/files/10345965/bad.printing.pdf)
Original file: [U4684 ...1594 Iveco Daily plató + ponyva megrendelő Bene.pdf](https://github.com/pdfarranger/pdfarranger/files/10345966/U4684.1594.Iveco.Daily.plato.%2B.ponyva.megrendelo.Bene.pdf)

The issue is not unique to these files, I tried to print a bunch of others with the same results; I attached these for reference only.

System and Versions
-------------------

-   PDF Arranger version: 1.9.2, downloaded from GitHub, portable version.
-   pikepdf version and where you get it:
    From the _About_ menu:  libqpdf 10.4.0, pikepdf 4.3.1, GTK 3.24.31 and Python 3.9.7 (downloaded the portable version, with these included)
-   OS name and version:
**Edition**: Windows 10 Pro
**Version**: 22H2
**Install date**: ‎2021. ‎05. ‎21.
**build nr.**	19045.2364; Windows Feature Experience Pack 120.2212.4190.0

**Comment by dreua** [comment]
Thank you for your great but report, I just tried the same on Linux but the results were good, therefore I assume this is a Windows issue. It would be nice if someone else could test this on Windows and report the results.

**Comment by aGrimRepoMan** [comment]
I hesitated replying, since my results on Windows are different, but still not as desired. This may just muddy the waters. However in the spirit of more data:

When I try to print either a modified but unsaved file from within pdfArranger, the resulting PDF output file is empty {0 bytes). Same result when I print a "saved-as" file. No GUI error message.  In both tests, the print dialogue displayed after clicking "print..." from pdfArranger menu shows "Printing from Wind32 application". In that dialogue I select "Microsoft Print to PDF" as the destination printer. Toggling the button "Let the app change my printing preferences" in the dialogue did not change the result.

- PDF arranger version: Same as originally reported by @galgogergo, but using .msi build. Downloaded it from https://github.com/pdfarranger/pdfarranger/releases/download/1.9.2/pdfarranger-1.9.2-windows-installer.msi 
- I'm running a newer version of Windows:	Windows 11 Home
  Version	22H2
  OS build	22621.963

**Comment by jeromerobert** [comment]
I can reproduce the bug reported by @galgogergo but not the one of @aGrimRepoMan. The bug is the same with PDFCreator and "Microsoft Print to PDF", so I guess it's either in GTK, either in PDF Arranger.
