### ISSUE TITLE
Look into replacing python-distutils-extra

### ISSUE THREAD

**Issue by dreua** [pdfarranger/pdfarranger#853]
When trying to introduce automatic update checking for the Flatpak build, I've been told that [intltool was dead](https://github.com/flathub/shared-modules/pull/245#issuecomment-1518719041). Maybe it's worth looking into alternatives before it breaks beneath us, not a high priority though.

According to https://wiki.gnome.org/Projects/GnomeCommon/Migration we should be able to replace it with gettext:

> intltoolize is obsolete: gettext 0.19.7 includes all the functionality GNOME projects used from intltool, so you should port from intltool to gettext.

**Comment by jeromerobert** [comment]
Thank you @TingPing for your PR. The problem is that we currently rely on `python-distutils-extra` which still use intltool. The `po/*.sh` are only used by translators. With the current=2.50 version of `python-distutils-extra`, removing `intltool` breaks PDF-Arranger `pip install`.

Also note that, `python-dist-utils` has moved:

- from https://launchpad.net/python-distutils-extra/
- to https://salsa.debian.org/python-team/packages/python-distutils-extra

6 years ago. See:

- https://salsa.debian.org/python-team/packages/python-distutils-extra/-/commit/52c167167cea707bbebb9a2d6cd400fa8796f69e

Many distributions (including Fedora) did not noticed it:

- https://repology.org/project/python-distutils-extra/packages

probably because PyPI is not updated:

- https://pypi.org/project/distutils-extra-python/

Now the next step would be to open a bug on https://bugs.debian.org as `python-distutils-extra` is managed as a native debian package but I'll first try that:

@bdrung Sorry to disturb you. Is there's any plan to move away from `intltool` in `python-distutils-extra`, as according to @TingPing, it's now deprecated ?

**Comment by TingPing** [comment]
This should all be trivial to replace. Translations are very simple, you just call `msgfmt` on them.

If you want a helper module this looks reasonable: https://github.com/breezy-team/setuptools-gettext/blob/master/setuptools_gettext/__init__.py
