### ISSUE TITLE
SAVE doesn't works. Always appears SAVE AS prompt.

### ISSUE THREAD

**Issue by MacPaKKo** [pdfarranger/pdfarranger#902]
After opening a PDF file, and editing or not it, clicking on SAVE button, or pressing CTRL+S, always acts as SAVE AS command, opening the saveas prompt window, moreover without any reference to the name of the opened file.

PdfArranger always opens files as UNTITLED, so on SAVE command it always ask for a SAVE AS.
I've tried with lots of pdf and jpeg files too.
------------

Expected behavior:
clicking on SAVE button, or pressing CTRL+S, it has to save the file overwriting the same file. An option to show overwriting file warning, should be useful as a preference.

System and Versions:
-   PDF Arranger version 1.9.2 download by GITHUB (msi installer)
-   OS Windows 11 Home - version 22H2 - Build 22621.1848

Thanks!
Adriano

**Comment by dreua** [comment]
Please use the search function: See https://github.com/pdfarranger/pdfarranger/issues/65 and https://github.com/pdfarranger/pdfarranger/issues/100

It should be prefilled with the opened file, however.

**Comment by MacPaKKo** [comment]
No, the filename box is empty. Not prefilled.
The filename is present in the title of the window  << UNTITLED(Senza Titolo*)-[nameOfOpenedFile] - PDF Arranger >>
![image](https://github.com/pdfarranger/pdfarranger/assets/14088855/ef61a447-10d7-4347-a7eb-8019a59c2f94)
WINDOWS 11
Thanks

**Comment by kbengs** [comment]
> the filename box is empty

In the coming 1.10 it should be fixed (prefilled). I have tested it in Windows 10 but not in 11.  If you like to test you can download a zip/msi here: https://github.com/pdfarranger/pdfarranger/actions/runs/5324297540

**Comment by MacPaKKo** [comment]
Tested 1.10 on windows 11. It's ok now, the filename box is prefilled.

**Comment by HubKing** [comment]
"Save" is the same as "Save As"? I opened a file that I downloaded from the Internet, removed the border, and clicked the "Save" button. What I expected was overwriting the file without a prompt. But when I tested it, both "Save" and "Save As" showed the dialogue. The name was filled by default, but it's annoying extra two steps as the save dialogue also showed an overwrite confirmation message box.

I tried to read the logic in the linked issues, but I still don't get the logic. Why doesn't it work like other Gnome applications? For example, if I create a new file and open it with Gnome's default text editor, type something, and click the "Save" menu, it just saves the file without any additional UI pop-ups.

**Comment by kbengs** [comment]
The current logic is that you import documents to a empty "workspace". The word "open" is not good. There has been an idea to rename it to "Import in new window". But I am still unsure what is best.

If you have "opened" several documents, you can't be sure which one you are going to overwrite when you save, that's why the dialog asks.

**Comment by HubKing** [comment]
> If you have "opened" several documents, you can't be sure which one you are going to overwrite when you save, that's why the dialog asks.

I had not thought about this case, because I have been opening a single PDF file at a time using the file manager's Open With feature. But, in my opinion, the app could simply treat the PDF as an already-saved workspace, if the user has opened only a single PDF file. It's just my guess, but probably, in most cases, users would edit a single PDF file, rather than trying to merge multiple PDF files, and they would expect that clicking "save" would apply the changes to the file that they have opened.

**Comment by chbacher** [comment]
Using Version 1.10.1 on Mint.
Same problem here as described above - I open the pdf file to modify. Rearrange and add pages and click on "Save" (which results exactly in the same as behavior as "Save as") -> Save dialogue window pops up in the "home" directory, no file names are displayed (empty).
Now I have to browse into the destination folder to overwrite the source file. Very time consuming and annoying (given the fact, that there is a "save as" option for the cases I need to create a new file).
Is there a solution?
